name = star_wars
description = Brings star wars to Minetest! It adds Jedi + Sith abilities (you choose wich side you are), working and craftable lightsabers and even blasters! Then we have Mandalorian stuff coming.
depends = default, dye, 3d_armor, 3d_armor_ip, 3d_armor_sfinv, 3d_armor_ui
optional_depends = illumination, wield3d
author = Reper11
title = Star Wars Mod
